/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-router. ‼️ DO NOT MODIFY THIS FILE ‼️
// It's recommended to commit this file.
// Make sure to add this file to your tsconfig.json file as an "includes" or "files" entry.

declare module 'vue-router/auto-routes' {
  import type {
    RouteRecordInfo,
    ParamValue,
    ParamValueOneOrMore,
    ParamValueZeroOrMore,
    ParamValueZeroOrOne,
  } from 'vue-router'

  /**
   * Route name map generated by unplugin-vue-router
   */
  export interface RouteNamedMap {
    '/': RouteRecordInfo<'/', '/', Record<never, never>, Record<never, never>>,
    '/ipr1/': RouteRecordInfo<'/ipr1/', '/ipr1', Record<never, never>, Record<never, never>>,
    '/ipr2/': RouteRecordInfo<'/ipr2/', '/ipr2', Record<never, never>, Record<never, never>>,
    '/old-kr-1/': RouteRecordInfo<'/old-kr-1/', '/old-kr-1', Record<never, never>, Record<never, never>>,
    '/zadanie1/': RouteRecordInfo<'/zadanie1/', '/zadanie1', Record<never, never>, Record<never, never>>,
    '/zadanie2/': RouteRecordInfo<'/zadanie2/', '/zadanie2', Record<never, never>, Record<never, never>>,
  }
}
